apiVersion: oran.o2imsop/v1alpha1
kind: O2imsRequest
metadata:
  labels:
    app.kubernetes.io/name: o2ims-test-operator
    app.kubernetes.io/managed-by: kustomize
  name: o2imsrequest-sample
spec:
  domain: 172.16.1.1
  port: 9000
  path: /o2ims-infrastructureInventory/v1/deploymentManagers/d4fe8587-531b-4d17-923b-e64fd762c62e
  